// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmZGibELvJ8X0xl2U7HDVkZAGy0bOgqrw',
    appId: '1:204584043230:web:4c4a6108a7478782d6b84f',
    messagingSenderId: '204584043230',
    projectId: 'prasad-48701',
    authDomain: 'prasad-48701.firebaseapp.com',
    storageBucket: 'prasad-48701.appspot.com',
    measurementId: 'G-H9RCCX5PE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQh5FSmfsfHBZhOrSQm3HhFpUzl1zdaqw',
    appId: '1:204584043230:android:53264193750e0943d6b84f',
    messagingSenderId: '204584043230',
    projectId: 'prasad-48701',
    storageBucket: 'prasad-48701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl1wBfouJnaiJjKJluOrRks8tJr0FBmt0',
    appId: '1:204584043230:ios:7e225513a5a26de9d6b84f',
    messagingSenderId: '204584043230',
    projectId: 'prasad-48701',
    storageBucket: 'prasad-48701.appspot.com',
    iosBundleId: 'com.example.gdnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl1wBfouJnaiJjKJluOrRks8tJr0FBmt0',
    appId: '1:204584043230:ios:969dcf7cb697021ad6b84f',
    messagingSenderId: '204584043230',
    projectId: 'prasad-48701',
    storageBucket: 'prasad-48701.appspot.com',
    iosBundleId: 'com.example.gdnotes.RunnerTests',
  );



// ...
}
